### ISSUE TITLE
Add 'sex' field to Person model

### ISSUE THREAD

**Issue by mrysav** [mrysav/geneac#33]
Current there is a field `gender` on the Person model that is a free-text field. I don't remember why I made the decision to call it that, but in practice it is used as a 'sex' field.

I wish to have an expressive way to document a person's gender identity as well as their biological sex for logging parentage, but does not exist. In my opinion the best way to handle this would be to add an additional sex field that works like this:

Person
- sex: restricted to to "male", "female", "other", "unknown" (default unknown)
- gender: optional free text field

A correct implementation of this issue would also include model specs/tests.

**Comment by chethanagopinath** [comment]
@mrysav Hi, would love to pick this up if possible!

**Comment by mrysav** [comment]
@chethanagopinath absolutely! Check out the CONTRIBUTING.md file for instructions on how to get setup and let me know if you have any questions, run into any issues, or need any clarification.

**Comment by chethanagopinath** [comment]
@mrysav Thank you so much! :) I'll be working on for HacktoberFest, very excited ! I shall set up soon and let you know if I run into any issues.

**Comment by chethanagopinath** [comment]
@mrysav Hi, since I am not the owner to the issue, I am not sure how to assign myself to the issue :/

**Comment by mrysav** [comment]
> @mrysav Hi, since I am not the owner to the issue, I am not sure how to assign myself to the issue :/

assigned you!

**Comment by chethanagopinath** [comment]
@mrysav Hi, so as per the new rules of Hacktoberfest, contributing to a repo which has topic, 'Hacktoberfest' or a label as 'hacktoberfest-accepted' are valid it seems. Since I really want to work on this issue and participate in Hacktoberfest, would you be willing to do either of these? Sorry about the trouble. Thanks!

**Comment by mrysav** [comment]
@chethanagopinath I added the hacktoberfest to the repo. I think that will be enough, but I can add the 'hacktoberfest-accepted' label to your PR(s) when they are merged as well.

Thanks for letting me know!

**Comment by chethanagopinath** [comment]
@mrysav Awesome! Thanks so much!

**Comment by chethanagopinath** [comment]
@mrysav Hi, really sorry for the delay :/ While looking at the Person model, I could not find a gender field, but I did find it within the person_dashboard.rb. There's also another field called person_field.rb, I'm super new to this, but which ones should I be checking, am I missing something :(?

**Comment by mrysav** [comment]
Not a problem at all, and thank you for asking! I apologize in advance if I over-explain these next parts but I'm not sure how familiar you are with Rails, so I'll give a comprehensive answer :)

You can see that there is a `gender` field on the Person model by looking at [the database schema](https://github.com/mrysav/geneac/blob/1a4f036091bc9eed25327aafad3e0c5bd8261d89/db/schema.rb#L84). [ActiveRecord](https://guides.rubyonrails.org/active_record_basics.html) hides the actual fields from the models, so you don't actually have to have a `gender` method inside the model to reference it, since it is a column in the Person table.

To generate a new a column/field for the Person model, you'd have to create a migration. You can see the [migration that created the Person model here](https://github.com/mrysav/geneac/blob/1a4f036091bc9eed25327aafad3e0c5bd8261d89/db/migrate/20180721145400_create_people.rb#L8).

Rails provides a lot of nice helpers for working with databases, such as migrations, which are what they sound like: the way you make modifications to the database. A migration for adding an extra `sex` field can be generated with the command:

```bash
rails generate migration AddSexToPerson sex:string
```

Rails is kind of magic, so it will pull out the table you want to modify (Person) from that command, and the `sex:string` part is the column name and type you want to add. This will create the migration you want! Now, assuming you [created the database and have the schema loaded](https://github.com/mrysav/geneac/blob/main/CONTRIBUTING.md#running-the-application-locally), you can run 

```bash
rails db:migrate
```

and the column will be added. And that's that!

Now that the column is added, there needs to be some way to edit it. Geneac uses [thoughtbot's 'administrate'](https://github.com/thoughtbot/administrate/blob/master/docs/getting_started.md) gem for this, and I really like it because it's simple and extensible. That's where the "dashboard" and "field" files are coming from. In this case, `person_field` is unrelated to the Person model in general - it's a field for editing a specific part of the Person model. In fact, the only file that needs to be edited is the Person dashboard - [right around here](https://github.com/mrysav/geneac/blob/1a4f036091bc9eed25327aafad3e0c5bd8261d89/app/dashboards/person_dashboard.rb#L15). You can see that `gender` already has a spot - you can copy that format for `sex`. This tells Administrate to what kind of a field to expect for that column of the model.

Then, you can add the `sex` field to the [SHOW_PAGE_ATTRIBUTES](https://github.com/mrysav/geneac/blob/1a4f036091bc9eed25327aafad3e0c5bd8261d89/app/dashboards/person_dashboard.rb#L43) and [FORM_ATTRIBUTES](https://github.com/mrysav/geneac/blob/1a4f036091bc9eed25327aafad3e0c5bd8261d89/app/dashboards/person_dashboard.rb#L62) lists. This tells Administrate to place the `sex` field on the page for displaying that particular person, as well as on the page for editing that person.

Now, when you look at the person in the Administrate interface, you can see the `sex` field!

Hopefully that is enough to get you started - I'd be happy to accept a PR just for what I've outlined above. However if you want to submit more PRs for that sweet, sweet Hacktoberfest t-shirt goodness, some areas you might consider are:

* Adding sex to the `[generate:testdata](https://github.com/mrysav/geneac/blob/main/lib/tasks/generate_testdata.rake)` task
* Displaying gender/sex somehow on the Person page outside of the admin interface (ie. [this page](https://geneac-demo.herokuapp.com/p/344476_marquita_mueller))
* Restricting the `sex` field to `male`, `female` or `other` (either with a model validation, [or an enum](https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html), although I've never used them myself)

**Comment by chethanagopinath** [comment]
@mrysav This is perfect! And no, I feel really encouraged to dig in more and work on it. I have worked with migrations a bit in that, I would first create the model, write out its attributes and then do the `rake db:migrate` step. Thank you for explaining :) Also, I will be submitting a PR and also work on the other three things that you have highlighted even if Hacktoberfest is over as I definitely want to learn more :)

**Comment by chethanagopinath** [comment]
@mrysav Hi, I wanted to check the sex field on the Administrate interface but I am not authorised to do so, I was also looking for admin users in the README but could not find it. Is there anywhere else where I should be looking to check this? (And thank you so much for such a detailed explanation of the steps I should be getting done, the process was extremely smooth!)

**Comment by mrysav** [comment]
@chethanagopinath 

1. You can make any user an administrator using `rake admin:grant[myemail@website.com]`. My mistake for not adding that to the documentation!

2. Yes please!

**Comment by chethanagopinath** [comment]
@mrysav No problem :) I am still trying to understand the magic of Rails, so when I ran the above command, I got this error `undefined method `admin=' for nil:NilClass`. Am I missing setting up anything?

**Comment by mrysav** [comment]
That means that the email you put between the `[ ]` doesn't exist in the
database yet. So you'll have to go to the sign up page first (ie.
http://localhost:5000/users/sign_up or however you are running the server)
and create the user.

Alternatively, you can run `rake generate:testdata` and it will create an
admin user with the email "mcfly@bttf.net" and password "thatsheavy"

**Comment by chethanagopinath** [comment]
@mrysav Right, I did that but I just found out that the second part of my migration did not populate the `change` method within the migration(the `sex:string` part) but I checked the Rails guide and I don't know what is missing with my syntax, so can I go ahead and add 
`add_column :person, :sex, :string` ?

**Comment by mrysav** [comment]
Odd! I’ve had that happen before too so yeah, that would be right if you are doing it manually.

**Comment by chethanagopinath** [comment]
@mrysav Oooo, I understood what happened, I noticed that all the other migrations had an `_` between the fieldname and the `to` in their names, and then I looked into the names of the migrations and they have migration names where the T is capitalised - like `AddProfilePhotoIdToPerson`. Mine was named `AddSextoPerson`. So I reran the migration and fixed that capitalisation issue and it now generates the field properly :)

**Comment by chethanagopinath** [comment]
@mrysav I have created a PR for the steps you've outlined above and I also wanted to work on adding the sex field to the `generate:testdata` task, could I just create a PR for it when I'm done or would that need to be another issue? I really appreciate how patient you have been with me, thank you so much!

**Comment by mrysav** [comment]
@chethanagopinath Looks great! I've merged the PR without comments!

You can feel free to do another PR and I'll count it towards this same issue. (I think Hacktoberfest is based on PRs, not issues; but if it needs to be another issue I can make it one)

**Comment by chethanagopinath** [comment]
@mrysav I just checked and seems like it is based on the PRs and not the issue itself :)  so I will work on this one next!

**Comment by chethanagopinath** [comment]
@mrysav Quick question about the rake task.
In this,
`person = Person.create!(first_name: is_female ? Faker::Name.female_first_name : Faker::Name.male_first_name,
                              last_name: Faker::Name.last_name,
                              gender: is_female ? 'Female' : 'Male',
                              bio: Faker::Quote.famous_last_words)
`
is it okay to add `sex` after `gender` and what should `gender` hold now that `sex` holds `female`, `male`, `other`, `unknown` ? (Also instead of unknown could we make it, `Prefer not to answer`?)

**Comment by mrysav** [comment]
To be honest, I'm not really sure! Since this is just a rake task that generates test data it isn't too important. Perhaps you could generate two separate values for `sex` and `gender`, but generate them the same way?

That's also a good point about using `Prefer not to answer` - however, in this case I think just leaving it blank makes more sense, because the focus of this application is not asking users for *their own* information - you are inputting information about your ancestors. So, if I were making an application that asks users for their sex/gender, then I would have a `Prefer not to answer` option, but in this case, I can just leave it blank if I don't know what sex eg. "Morgan Smith" from the 1800s was. There is also a possibility that some person is a non-binary sex, and even though I originally suggested "unknown", I think I agree with not including that and instead just leaving "sex" as free text field. What do you think?

So to continue that, you could make functions like this:

```ruby
def generate_sex
  # There can be other values here if you feel it is appropriate
  ['', 'male', 'female'].sample
end

def generate_gender
  # again, substitute values you feel appropriate here
  ['', 'male', 'female', 'transgender', 'gender neutral', 'non-binary', 'agender'].sample
end
```

**Comment by chethanagopinath** [comment]
@mrysav Perfect! I agree with both of those. So within the loop that creates random `Person` data, I will create the two generator functions for generating sex and gender and will call them. And since `sex` and `gender` are both free text fields now, I don't need to worry too much about specificities like `Unknown` or `Wish to not answer` or stuff like that.

**Comment by chethanagopinath** [comment]
@mrysav Thank you so much for being so patient with me and encouraging me to go on! This was my last PR for Hacktoberfest :')

**Comment by mrysav** [comment]
@chethanagopinath You are very welcome! This Hacktoberfest was my first time having contributors to my projects on Github - so thank you for being a part of that, and thank you for helping me make Geneac a more inclusive project!

Given our prior conversations, I think the only remaining task would be to display this information somehow on each Person's user-facing page. Unfortunately that page is something I have historically changed a lot since I am not very good at design and I tend to move it around a lot. But right now the biggest gap I see is that the "generic" photo for a Person is a silhouette of Abe Lincoln - which is not ideal since obviously not everyone is male.

https://geneac-demo.herokuapp.com/p/452795_edgardo_koss?t=family

Perhaps there should be multiple different options for displaying photos based on sex? Ie. one photo for males, one for females, one for other common sexes and/or gender identities... etc. I'm open to suggestions!

**Comment by chethanagopinath** [comment]
@mrysav Hi! Sorry about being this late, I had to catch up on coursework and had finals and at school and such, I was also wondering if I can continue working on the issue. If so, I had a question about where I could the user-facing page for each person. I tried clicking on the above link to check, but it says that the app is down. I would like to check it on my local instance of Geneac.

**Comment by mrysav** [comment]
@chethanagopinath Hello! No problem at all, I also had coursework and other life stuff, so I only recently started making commits as well. And in fact, my Rails 6.1 upgrade last weekend introduced some migrations that I forgot to apply to the demo site. So that is back up now and should be working!

https://geneac-demo.herokuapp.com/p/452795_edgardo_koss?t=family

I like the idea of having a bunch of non-gendered photos to represent Person models in different contexts!

Feel free to hack away and let me know if you have any questions!

**Comment by mrysav** [comment]
@chethanagopinath Hello! I am resolving this issue and creating others for this year's Hacktoberfest.

If you're interested in contributing again I'd be happy to accept your PR - feel free to claim another issue!
