### ISSUE TITLE
Migrate the rest of the minitest tests to RSpec

### ISSUE THREAD

**Issue by mrysav** [mrysav/geneac#35]
There is still a `test/` directory from when this project used minitest, and there are several tests there that have not been moved over to RSpec yet.

It should be fairly straightforward to add these tests to an appropriate spec. Then we can delete `test/`

**Comment by emgreen33** [comment]
@mrysav would love to help finish the test to rspec migration here

**Comment by mrysav** [comment]
@emgreen33 Sounds great! I'll assign the issue to you. Let me know if you need any background or have any questions!
