### ISSUE TITLE
Add "birthday" widget to home page

### ISSUE THREAD

**Issue by mrysav** [mrysav/geneac#66]
The home page has one 'widget' right now - Recent Updates. I've always thought that it would be cool to have a "birthdays" widget that showed which People in the database have a birthday coming up in the next ~1 week or so.

![recent_updates](https://user-images.githubusercontent.com/297507/134447792-19e3e33b-6e33-4f4c-97e4-4b2d9a0ae3cb.png)

### 1. Get a list of people with birthdays coming up

If a **Person** has a birthday in the database, the birthday is stored as a **Fact**. You can access this **Fact** as `person.birth_date`. On each **Fact**, the date is not actually stored as a real DateTime object because there are huge variances in what a Date might actually be stored as during research. The `date_string` is parsed into a usable Date after the record is retrieved from the database.

With that in mind, you can't just query the database. I think, naively, you could make do with something like this (syntax may not be correct):

```ruby
today = Date.today
Person.all.select { |p| p.birth_date&.date.day == today.day && p.birth_date&.date.month == today.month }
```

However, the performance would be pretty bad. *I would accept a solution that looked kind of like this (cleaned up a bit)*, but you get bonus points if you cache this somehow, or otherwise avoid making expensive calls.

This logic can be added to either the model or controller.

**A test is required to verify correct behavior for this part.**

### 2. Plumb the data to the view

You can add some logic to `home_controller.rb` to get this data visible to the view. I would also accept a more dynamic, AJAX-y widget, but that is not required.

**A test is required to verify correct behavior for this part.**

### 3. Make the widget

You can add the view code to `views/home/index.haml`. It doesn't need to be anything fancy - it can just be a list of people. It should roughly match the style of the other parts of the page.

At minimum, this should display:

1. The person's name
2. A link to the person (this can be combined with the name)
3. The birth date

**Comment by lucygilbert** [comment]
Hey, I could have a shot at this, if you like?

**Comment by mrysav** [comment]
@lucygilbert Sounds great! I will assign the issue to you. :smiley:

You can check out [CONTRIBUTING.md](https://github.com/mrysav/geneac/blob/main/CONTRIBUTING.md) to get started. If you have any questions about the project or getting setup, let me know. Finally, if you want to split the work into multiple PRs in order to qualify for the Hacktoberfest t-shirt, as long as they are independently reviewable, I am OK with that!

**Comment by lucygilbert** [comment]
Cool, thanks, I've had a read through your docs and gotten set up. Everything seems to be working right, the Docker setup was really straight-forward.

I have an idea for a pure SQL solution to the query, so I'll raise a PR with some scopes for the Fact model first, then a PR for implementing the widget.

**Comment by mrysav** [comment]
This is done! 🎉
